import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import styles from "./styles.module.css";
import StickyNavbar from "./components/stickyNavbar";
import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Nicholas Hansen",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  1;
  return (
    <html lang="en">
      <head></head>
      <body className={inter.className}>
        <div className=" flex ">
          <StickyNavbar></StickyNavbar>
          {children}
        </div>
      </body>
    </html>
  );
}
