import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import styles from "./styles.module.css";
import Header from "./components/header";
import Link from "next/link";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Analytics } from "@vercel/analytics/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Nicholas Hansen",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  1;

  return (
    <html lang="en">
      <head></head>
      <body className={inter.className} /* suppressHydrationWarning={true} */>
        <SpeedInsights />
        <Analytics />
        <div className="sm:flex md:flex">
          <div className="bg-orange/80 backdrop-blur-sm top-0 fixed w-screen z-10 md:px-40 px-0 py-3 md:block flex justify-center">
            <Header></Header>
          </div>
          <div className="">{children}</div>
        </div>
      </body>
    </html>
  );
}
